# Generated by Django 6.0.1 on 2026-01-29 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hahu_id', models.IntegerField(unique=True)),
                ('url', models.URLField(max_length=500)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('no_price', models.BooleanField(default=False)),
                ('is_rentable', models.BooleanField(default=False)),
                ('fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('engine_cc', models.IntegerField(blank=True, null=True)),
                ('power_le', models.IntegerField(blank=True, null=True)),
                ('power_kw', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True)),
                ('description_snippet', models.TextField(blank=True)),
                ('seller', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dummy_ads',
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('expected_cars', models.IntegerField()),
                ('actual_scraped', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
            options={
                'db_table': 'scrape_logs',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hahu_id', models.IntegerField(unique=True)),
                ('url', models.URLField(max_length=500)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('no_price', models.BooleanField(default=False)),
                ('is_rentable', models.BooleanField(default=False)),
                ('fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('engine_cc', models.IntegerField(blank=True, null=True)),
                ('power_le', models.IntegerField(blank=True, null=True)),
                ('power_kw', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True)),
                ('description_snippet', models.TextField(blank=True)),
                ('seller', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
