# Generated by Django 6.0.1 on 2026-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mae', models.IntegerField()),
                ('r2_score', models.FloatField()),
            ],
            options={
                'db_table': 'ai_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
